#!/bin/sh
git filter-branch --env-filter " \
    export GIT_AUTHOR_NAME='Benjamin C Meyer'; \
    export GIT_AUTHOR_EMAIL='ben@meyerhome.net'; \
    export GIT_COMMITTER_NAME='Benjamin C Meyer'; \
    export GIT_COMMITTER_EMAIL='ben@meyerhome.net'; \
" HEAD
