#!/bin/sh
if [ `uname` = "Linux" ] ; then
    ./configure -developer-build -opensource -fast -no-qt3support -optimized-qmake -prefix $PWD
else
    ./configure -developer-build -opensource -fast -no-qt3support -optimized-qmake -prefix $PWD -debug-and-release
fi
